In [27]:
import pandas_datareader.data as web
import datetime

In [28]:
start = datetime.datetime(2021,9,1)
end = datetime.datetime(2021,9,30)

In [29]:
google = web.DataReader("GOOGL",'yahoo',start,end)
google
#vos = web.DataReader("VOS",'ssi',start,end)
#vos

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-08-31,2903.429932,2885.620117,2902.939941,2893.949951,1122400,2893.949951
2021-09-01,2925.080078,2897.669922,2900.000000,2904.310059,1096800,2904.310059
2021-09-02,2910.389893,2863.699951,2904.320068,2865.739990,1617100,2865.739990
2021-09-03,2883.100098,2848.010010,2861.610107,2874.790039,992500,2874.790039
2021-09-07,2891.300049,2872.379883,2876.689941,2885.610107,1006200,2885.610107
2021-09-08,2888.000000,2860.000000,2882.000000,2873.820068,917200,2873.820068
2021-09-09,2886.209961,2863.550049,2876.810059,2870.820068,765700,2870.820068
2021-09-10,2894.370117,2814.760010,2884.250000,2817.520020,1840700,2817.520020
2021-09-13,2859.000000,2825.000000,2838.989990,2846.649902,1104700,2846.649902
2021-09-14,2867.260010,2835.000000,2859.909912,2850.889893,983700,2850.889893
2021-09-15,2889.010010,2826.949951,2855.429932,2888.590088,1370400,2888.590088
2021-09-16,2886.000000,2848.030029,2879.010010,2872.199951,1309500,2872.199951
2021-09-17,2869.000000,2809.399902,2860.610107,2816.000000,2666800,2816.000000
2021-09-20,2780.000000,2726.439941,2763.229980,2774.389893,2325900,2774.389893
2021-09-21,2800.229980,2765.560059,2794.989990,2780.659912,1266600,2780.659912
2021-09-22,2817.739990,2771.030029,2786.080078,2805.669922,1252800,2805.669922
2021-09-23,2833.929932,2808.030029,2819.750000,2824.320068,1047600,2824.320068
2021-09-24,2846.610107,2804.820068,2810.770020,2844.300049,1148700,2844.300049
2021-09-27,2838.770020,2801.350098,2816.090088,2821.439941,1094100,2821.439941
2021-09-28,2781.929932,2707.199951,2773.100098,2716.600098,2288600,2716.600098
2021-09-29,2743.020020,2677.300049,2739.600098,2687.070068,1539600,2687.070068

In [30]:
google.head()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-08-31,2903.429932,2885.620117,2902.939941,2893.949951,1122400,2893.949951
2021-09-01,2925.080078,2897.669922,2900.000000,2904.310059,1096800,2904.310059
2021-09-02,2910.389893,2863.699951,2904.320068,2865.739990,1617100,2865.739990
2021-09-03,2883.100098,2848.010010,2861.610107,2874.790039,992500,2874.790039
2021-09-07,2891.300049,2872.379883,2876.689941,2885.610107,1006200,2885.610107

In [31]:
google.describe()

,High,Low,Open,Close,Volume,Adj Close
count,21.000000,21.000000,21.000000,21.000000,2.100000e+01,21.000000
mean,2856.875244,2814.847621,2842.199068,2834.063814,1.369410e+06,2834.063814
std,48.539056,58.250899,49.136534,57.106756,5.103125e+05,57.106756
min,2743.020020,2677.300049,2739.600098,2687.070068,7.657000e+05,2687.070068
25%,2833.929932,2801.350098,2810.770020,2816.000000,1.047600e+06,2816.000000
50%,2869.000000,2825.000000,2859.909912,2846.649902,1.148700e+06,2846.649902
75%,2889.010010,2860.000000,2879.010010,2873.820068,1.539600e+06,2873.820068
max,2925.080078,2897.669922,2904.320068,2904.310059,2.666800e+06,2904.310059

In [32]:
def inc_dec(c, o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

google["Status"]=[inc_dec(c,o) for c, o in zip(google.Close,google.Open)]
google["Middle"]=(google.Open + google.Close)/2
google["Height"]=abs(-google.Open + google.Close)
google

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2021-08-31,2903.429932,2885.620117,2902.939941,2893.949951,1122400,2893.949951,Decrease,2898.444946,8.989990
2021-09-01,2925.080078,2897.669922,2900.000000,2904.310059,1096800,2904.310059,Increase,2902.155029,4.310059
2021-09-02,2910.389893,2863.699951,2904.320068,2865.739990,1617100,2865.739990,Decrease,2885.030029,38.580078
2021-09-03,2883.100098,2848.010010,2861.610107,2874.790039,992500,2874.790039,Increase,2868.200073,13.179932
2021-09-07,2891.300049,2872.379883,2876.689941,2885.610107,1006200,2885.610107,Increase,2881.150024,8.920166
2021-09-08,2888.000000,2860.000000,2882.000000,2873.820068,917200,2873.820068,Decrease,2877.910034,8.179932
2021-09-09,2886.209961,2863.550049,2876.810059,2870.820068,765700,2870.820068,Decrease,2873.815063,5.989990
2021-09-10,2894.370117,2814.760010,2884.250000,2817.520020,1840700,2817.520020,Decrease,2850.885010,66.729980
2021-09-13,2859.000000,2825.000000,2838.989990,2846.649902,1104700,2846.649902,Increase,2842.819946,7.659912
2021-09-14,2867.260010,2835.000000,2859.909912,2850.889893,983700,2850.889893,Decrease,2855.399902,9.020020
2021-09-15,2889.010010,2826.949951,2855.429932,2888.590088,1370400,2888.590088,Increase,2872.010010,33.160156
2021-09-16,2886.000000,2848.030029,2879.010010,2872.199951,1309500,2872.199951,Decrease,2875.604980,6.810059
2021-09-17,2869.000000,2809.399902,2860.610107,2816.000000,2666800,2816.000000,Decrease,2838.305054,44.610107
2021-09-20,2780.000000,2726.439941,2763.229980,2774.389893,2325900,2774.389893,Increase,2768.809937,11.159912
2021-09-21,2800.229980,2765.560059,2794.989990,2780.659912,1266600,2780.659912,Decrease,2787.824951,14.330078
2021-09-22,2817.739990,2771.030029,2786.080078,2805.669922,1252800,2805.669922,Increase,2795.875000,19.589844
2021-09-23,2833.929932,2808.030029,2819.750000,2824.320068,1047600,2824.320068,Increase,2822.035034,4.570068
2021-09-24,2846.610107,2804.820068,2810.770020,2844.300049,1148700,2844.300049,Increase,2827.535034,33.530029
2021-09-27,2838.770020,2801.350098,2816.090088,2821.439941,1094100,2821.439941,Increase,2818.765015,5.349854
2021-09-28,2781.929932,2707.199951,2773.100098,2716.600098,2288600,2716.600098,Decrease,2744.850098,56.500000
2021-09-29,2743.020020,2677.300049,2739.600098,2687.070068,1539600,2687.070068,Decrease,2713.335083,52.530029

In [33]:
from bokeh.plotting import figure, show, output_file

p = figure(x_axis_type='datetime', width=1000, height=300)
p.title.text = "Candlestick Chart"

hours_12 = 12 * 60 * 60 * 1000

#tăng
p.rect(google.index[google.Status=="Increase"],google.Middle[google.Status=="Increase"],
   hours_12, google.Height[google.Status=="Increase"],fill_color="#CCFFFF",
   line_color="black")
#giảm
p.rect(google.index[google.Status=="Decrease"],google.Middle[google.Status=="Decrease"],
   hours_12, google.Height[google.Status=="Decrease"],fill_color="#FF3333",
   line_color="black")

p.segment(google.index, google.High, google.index, google.Low, color="Black")

output_file("chart.html")
show(p)